import assert from "node:assert/strict";
import test from "node:test";

import { hasAmpersandCharacter } from "./has-ampersand-character";
import { hasAsteriskCharacter } from "./has-asterisk-character";
import { hasAtSymbolCharacter } from "./has-at-symbol-character";
import { hasCaretCharacter } from "./has-caret-character";
import { hasCloseBraceCharacter } from "./has-close-brace-character";
import { hasCloseParenthesisCharacter } from "./has-close-parenthesis-character";
import { hasCommaCharacter } from "./has-comma-character";
import { hasDollarCharacter } from "./has-dollar-character";
import { hasEqualsCharacter } from "./has-equals-character";
import { hasExclamationCharacter } from "./has-exclamation-character";
import { hasFourDigitCharacter } from "./has-four-digit-character";
import { hasGreaterThanCharacter } from "./has-greater-than-character";
import { hasHyphenCharacter } from "./has-hyphen-character";
import { hasLessThanCharacter } from "./has-less-than-character";
import { hasOneDigitCharacter } from "./has-one-digit-character";
import { hasOpenBraceCharacter } from "./has-open-brace-character";
import { hasOpenParenthesisCharacter } from "./has-open-parenthesis-character";
import { hasPercentCharacter } from "./has-percent-character";
import { hasPeriodCharacter } from "./has-period-character";
import { hasPipeCharacter } from "./has-pipe-character";
import { hasPlusCharacter } from "./has-plus-character";
import { hasQuestionMarkCharacter } from "./has-question-mark-character";
import { hasThreeDigitCharacter } from "./has-three-digit-character";
import { hasTildeCharacter } from "./has-tilde-character";
import { hasTwoDigitCharacter } from "./has-two-digit-character";

test("detects digit and punctuation characters", () => {
  assert.equal(hasFourDigitCharacter("4"), true);
  assert.equal(hasThreeDigitCharacter("3"), true);
  assert.equal(hasTwoDigitCharacter("2"), true);
  assert.equal(hasOneDigitCharacter("1"), true);
  assert.equal(hasGreaterThanCharacter(">"), true);
  assert.equal(hasLessThanCharacter("<"), true);
  assert.equal(hasDollarCharacter("$"), true);
  assert.equal(hasCaretCharacter("^"), true);
  assert.equal(hasAtSymbolCharacter("@"), true);
  assert.equal(hasTildeCharacter("~"), true);
  assert.equal(hasPipeCharacter("|"), true);
  assert.equal(hasAmpersandCharacter("&"), true);
  assert.equal(hasPercentCharacter("%"), true);
  assert.equal(hasAsteriskCharacter("*"), true);
  assert.equal(hasEqualsCharacter("="), true);
  assert.equal(hasPlusCharacter("+"), true);
  assert.equal(hasHyphenCharacter("-"), true);
  assert.equal(hasQuestionMarkCharacter("?"), true);
  assert.equal(hasExclamationCharacter("!"), true);
  assert.equal(hasPeriodCharacter("."), true);
  assert.equal(hasCommaCharacter(","), true);
  assert.equal(hasCloseParenthesisCharacter(")"), true);
  assert.equal(hasOpenParenthesisCharacter("("), true);
  assert.equal(hasCloseBraceCharacter("}"), true);
  assert.equal(hasOpenBraceCharacter("{"), true);
});

test("returns false when the character is absent", () => {
  const missing = "abc";
  assert.equal(hasFourDigitCharacter(missing), false);
  assert.equal(hasThreeDigitCharacter(missing), false);
  assert.equal(hasTwoDigitCharacter(missing), false);
  assert.equal(hasOneDigitCharacter(missing), false);
  assert.equal(hasGreaterThanCharacter(missing), false);
  assert.equal(hasLessThanCharacter(missing), false);
  assert.equal(hasDollarCharacter(missing), false);
  assert.equal(hasCaretCharacter(missing), false);
  assert.equal(hasAtSymbolCharacter(missing), false);
  assert.equal(hasTildeCharacter(missing), false);
  assert.equal(hasPipeCharacter(missing), false);
  assert.equal(hasAmpersandCharacter(missing), false);
  assert.equal(hasPercentCharacter(missing), false);
  assert.equal(hasAsteriskCharacter(missing), false);
  assert.equal(hasEqualsCharacter(missing), false);
  assert.equal(hasPlusCharacter(missing), false);
  assert.equal(hasHyphenCharacter(missing), false);
  assert.equal(hasQuestionMarkCharacter(missing), false);
  assert.equal(hasExclamationCharacter(missing), false);
  assert.equal(hasPeriodCharacter(missing), false);
  assert.equal(hasCommaCharacter(missing), false);
  assert.equal(hasCloseParenthesisCharacter(missing), false);
  assert.equal(hasOpenParenthesisCharacter(missing), false);
  assert.equal(hasCloseBraceCharacter(missing), false);
  assert.equal(hasOpenBraceCharacter(missing), false);
});
