const ERROR_CODES = { BAD_REQUEST: 'BAD_REQUEST', UNAUTHORIZED: 'UNAUTHORIZED', FORBIDDEN: 'FORBIDDEN', NOT_FOUND: 'NOT_FOUND', CONFLICT: 'CONFLICT', INTERNAL_ERROR: 'INTERNAL_ERROR', VALIDATION_ERROR: 'VALIDATION_ERROR' } as const;
type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export { ERROR_CODES, ErrorCode };
