/**
 * Infinite Sequence Iterator
 *
 * A utility for creating and safely consuming infinite sequences using
 * JavaScript generators. Provides common mathematical sequences and
 * helper functions for safe iteration with built-in limits.
 *
 * @module infinite-sequence
 */

/**
 * Creates an infinite sequence of natural numbers starting from a given value.
 * @param start - Starting number (default: 0)
 */
export function* naturals(start = 0): Generator<number, never, unknown> {
  let n = start;
  while (true) {
    yield n++;
  }
}

/**
 * Creates an infinite Fibonacci sequence.
 */
export function* fibonacci(): Generator<number, never, unknown> {
  let [a, b] = [0, 1];
  while (true) {
    yield a;
    [a, b] = [b, a + b];
  }
}

/**
 * Creates an infinite sequence of prime numbers using a sieve approach.
 */
export function* primes(): Generator<number, never, unknown> {
  const isPrime = (n: number): boolean => {
    if (n < 2) return false;
    if (n === 2) return true;
    if (n % 2 === 0) return false;
    for (let i = 3; i <= Math.sqrt(n); i += 2) {
      if (n % i === 0) return false;
    }
    return true;
  };

  let candidate = 2;
  while (true) {
    if (isPrime(candidate)) {
      yield candidate;
    }
    candidate++;
  }
}

/**
 * Creates an infinite sequence by repeatedly applying a function.
 * @param fn - Transformation function applied to previous value
 * @param seed - Initial value
 */
export function* iterate<T>(fn: (value: T) => T, seed: T): Generator<T, never, unknown> {
  let current = seed;
  while (true) {
    yield current;
    current = fn(current);
  }
}

/**
 * Creates an infinite sequence that cycles through the given values.
 * @param values - Array of values to cycle through
 */
export function* cycle<T>(values: T[]): Generator<T, never, unknown> {
  if (values.length === 0) {
    throw new Error("Cannot cycle an empty array");
  }
  let index = 0;
  while (true) {
    yield values[index % values.length];
    index++;
  }
}

/**
 * Creates an infinite sequence where each element is generated by a function.
 * @param fn - Function that receives the index and returns the value
 */
export function* generate<T>(fn: (index: number) => T): Generator<T, never, unknown> {
  let i = 0;
  while (true) {
    yield fn(i++);
  }
}

// === Safe Iteration Utilities ===

/**
 * Takes the first n elements from an iterator.
 * This is the PRIMARY safe consumption method for infinite sequences.
 * @param n - Maximum number of elements to take
 * @param iter - Source iterator (can be infinite)
 * @returns Array of at most n elements
 */
export function take<T>(n: number, iter: Iterable<T>): T[] {
  const result: T[] = [];
  let count = 0;
  for (const value of iter) {
    if (count >= n) break;
    result.push(value);
    count++;
  }
  return result;
}

/**
 * Takes elements from an iterator while a predicate holds true.
 * Stops as soon as the predicate returns false.
 * @param predicate - Condition to check for each element
 * @param iter - Source iterator (can be infinite)
 */
export function takeWhile<T>(predicate: (value: T) => boolean, iter: Iterable<T>): T[] {
  const result: T[] = [];
  for (const value of iter) {
    if (!predicate(value)) break;
    result.push(value);
  }
  return result;
}

/**
 * Drops the first n elements and returns the rest (up to a limit).
 * @param n - Number of elements to skip
 * @param limit - Maximum elements to collect after skipping
 * @param iter - Source iterator (can be infinite)
 */
export function drop<T>(n: number, limit: number, iter: Iterable<T>): T[] {
  const result: T[] = [];
  let count = 0;
  let collected = 0;
  for (const value of iter) {
    if (count < n) {
      count++;
      continue;
    }
    if (collected >= limit) break;
    result.push(value);
    collected++;
  }
  return result;
}

/**
 * Filters elements from an iterator (with a safety limit).
 * @param predicate - Filter condition
 * @param limit - Maximum elements to return
 * @param iter - Source iterator (can be infinite)
 */
export function filter<T>(
  predicate: (value: T) => boolean,
  limit: number,
  iter: Iterable<T>
): T[] {
  const result: T[] = [];
  for (const value of iter) {
    if (result.length >= limit) break;
    if (predicate(value)) {
      result.push(value);
    }
  }
  return result;
}

/**
 * Maps a function over an iterator (with a safety limit).
 * @param fn - Transformation function
 * @param limit - Maximum elements to process
 * @param iter - Source iterator (can be infinite)
 */
export function map<T, U>(
  fn: (value: T) => U,
  limit: number,
  iter: Iterable<T>
): U[] {
  const result: U[] = [];
  let count = 0;
  for (const value of iter) {
    if (count >= limit) break;
    result.push(fn(value));
    count++;
  }
  return result;
}

/**
 * Reduces elements from an iterator (with a safety limit).
 * @param fn - Reducer function
 * @param initial - Initial accumulator value
 * @param limit - Maximum elements to process
 * @param iter - Source iterator (can be infinite)
 */
export function reduce<T, U>(
  fn: (acc: U, value: T) => U,
  initial: U,
  limit: number,
  iter: Iterable<T>
): U {
  let acc = initial;
  let count = 0;
  for (const value of iter) {
    if (count >= limit) break;
    acc = fn(acc, value);
    count++;
  }
  return acc;
}

/**
 * Zips two iterators together (with a safety limit).
 * @param limit - Maximum pairs to produce
 * @param iterA - First iterator
 * @param iterB - Second iterator
 */
export function zip<A, B>(
  limit: number,
  iterA: Iterable<A>,
  iterB: Iterable<B>
): [A, B][] {
  const result: [A, B][] = [];
  const a = iterA[Symbol.iterator]();
  const b = iterB[Symbol.iterator]();
  let count = 0;
  while (count < limit) {
    const nextA = a.next();
    const nextB = b.next();
    if (nextA.done || nextB.done) break;
    result.push([nextA.value, nextB.value]);
    count++;
  }
  return result;
}
