/**
 * API error code constants for consistent TaskFlow API error payloads.
 * Use these named error codes instead of magic strings for consistency.
 */

// General errors
export const INTERNAL_ERROR = "INTERNAL_ERROR";
export const SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
export const GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT";
export const UNKNOWN_ERROR = "UNKNOWN_ERROR";

// Authentication & Authorization errors
export const UNAUTHORIZED = "UNAUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const TOKEN_INVALID = "TOKEN_INVALID";
export const TOKEN_MISSING = "TOKEN_MISSING";
export const INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS";

// Validation errors
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const INVALID_INPUT = "INVALID_INPUT";
export const MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD";
export const INVALID_EMAIL = "INVALID_EMAIL";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT";
export const PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK";
export const INVALID_PHONE = "INVALID_PHONE";
export const INVALID_URL = "INVALID_URL";
export const INVALID_DATE = "INVALID_DATE";
export const INVALID_UUID = "INVALID_UUID";
export const INVALID_JSON = "INVALID_JSON";
export const INVALID_QUERY_PARAM = "INVALID_QUERY_PARAM";
export const INVALID_PAGE = "INVALID_PAGE";
export const INVALID_PAGE_SIZE = "INVALID_PAGE_SIZE";
export const INVALID_SORT_FIELD = "INVALID_SORT_FIELD";
export const INVALID_SORT_ORDER = "INVALID_SORT_ORDER";
export const INVALID_FILTER = "INVALID_FILTER";

// Resource errors
export const NOT_FOUND = "NOT_FOUND";
export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const TASK_NOT_FOUND = "TASK_NOT_FOUND";
export const PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND";
export const PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND";
export const FILE_NOT_FOUND = "FILE_NOT_FOUND";
export const MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND";
export const NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND";
export const REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND";

// Conflict errors
export const CONFLICT = "CONFLICT";
export const RESOURCE_CONFLICT = "RESOURCE_CONFLICT";
export const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
export const USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
export const PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS";
export const DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE";
export const VERSION_CONFLICT = "VERSION_CONFLICT";
export const OPTIMISTIC_LOCK_FAILURE = "OPTIMISTIC_LOCK_FAILURE";

// State errors
export const INVALID_STATE = "INVALID_STATE";
export const INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION";
export const TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED";
export const PROPOSAL_ALREADY_ACCEPTED = "PROPOSAL_ALREADY_ACCEPTED";
export const PAYMENT_ALREADY_PROCESSED = "PAYMENT_ALREADY_PROCESSED";
export const RESOURCE_LOCKED = "RESOURCE_LOCKED";

// Rate limiting & quota errors
export const RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED";
export const QUOTA_EXCEEDED = "QUOTA_EXCEEDED";
export const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE";
export const PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE";

// File & upload errors
export const FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR";
export const FILE_TOO_LARGE = "FILE_TOO_LARGE";
export const INVALID_FILE_TYPE = "INVALID_FILE_TYPE";
export const FILE_CORRUPTED = "FILE_CORRUPTED";
export const UPLOAD_FAILED = "UPLOAD_FAILED";
export const STORAGE_ERROR = "STORAGE_ERROR";

// External service errors
export const EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR";
export const PAYMENT_GATEWAY_ERROR = "PAYMENT_GATEWAY_ERROR";
export const EMAIL_SERVICE_ERROR = "EMAIL_SERVICE_ERROR";
export const SMS_SERVICE_ERROR = "SMS_SERVICE_ERROR";
export const DATABASE_ERROR = "DATABASE_ERROR";
export const CACHE_ERROR = "CACHE_ERROR";
export const THIRD_PARTY_API_ERROR = "THIRD_PARTY_API_ERROR";

/**
 * Consolidated error code constants object for convenient lookup.
 */
export const ErrorCodes = {
  // General
  INTERNAL_ERROR,
  SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT,
  UNKNOWN_ERROR,
  // Auth
  UNAUTHORIZED,
  FORBIDDEN,
  TOKEN_EXPIRED,
  TOKEN_INVALID,
  TOKEN_MISSING,
  INSUFFICIENT_PERMISSIONS,
  // Validation
  VALIDATION_ERROR,
  INVALID_INPUT,
  MISSING_REQUIRED_FIELD,
  INVALID_EMAIL,
  INVALID_PASSWORD,
  PASSWORD_TOO_SHORT,
  PASSWORD_TOO_WEAK,
  INVALID_PHONE,
  INVALID_URL,
  INVALID_DATE,
  INVALID_UUID,
  INVALID_JSON,
  INVALID_QUERY_PARAM,
  INVALID_PAGE,
  INVALID_PAGE_SIZE,
  INVALID_SORT_FIELD,
  INVALID_SORT_ORDER,
  INVALID_FILTER,
  // Resource
  NOT_FOUND,
  RESOURCE_NOT_FOUND,
  USER_NOT_FOUND,
  TASK_NOT_FOUND,
  PROPOSAL_NOT_FOUND,
  PAYMENT_NOT_FOUND,
  FILE_NOT_FOUND,
  MESSAGE_NOT_FOUND,
  NOTIFICATION_NOT_FOUND,
  REVIEW_NOT_FOUND,
  // Conflict
  CONFLICT,
  RESOURCE_CONFLICT,
  EMAIL_ALREADY_EXISTS,
  USERNAME_ALREADY_EXISTS,
  PHONE_ALREADY_EXISTS,
  DUPLICATE_RESOURCE,
  VERSION_CONFLICT,
  OPTIMISTIC_LOCK_FAILURE,
  // State
  INVALID_STATE,
  INVALID_STATUS_TRANSITION,
  TASK_ALREADY_COMPLETED,
  PROPOSAL_ALREADY_ACCEPTED,
  PAYMENT_ALREADY_PROCESSED,
  RESOURCE_LOCKED,
  // Rate limiting
  RATE_LIMIT_EXCEEDED,
  QUOTA_EXCEEDED,
  TOO_MANY_REQUESTS,
  REQUEST_TOO_LARGE,
  PAYLOAD_TOO_LARGE,
  // File
  FILE_UPLOAD_ERROR,
  FILE_TOO_LARGE,
  INVALID_FILE_TYPE,
  FILE_CORRUPTED,
  UPLOAD_FAILED,
  STORAGE_ERROR,
  // External
  EXTERNAL_SERVICE_ERROR,
  PAYMENT_GATEWAY_ERROR,
  EMAIL_SERVICE_ERROR,
  SMS_SERVICE_ERROR,
  DATABASE_ERROR,
  CACHE_ERROR,
  THIRD_PARTY_API_ERROR,
} as const;

export default ErrorCodes;
