/**
 * Notification type constants for TaskFlow API notification payloads.
 * Use these named constants instead of magic strings for consistency.
 */

// General notification types
export const INFO = "INFO";
export const SUCCESS = "SUCCESS";
export const WARNING = "WARNING";
export const ERROR = "ERROR";
export const CRITICAL = "CRITICAL";

// Task notification types
export const TASK_CREATED = "TASK_CREATED";
export const TASK_UPDATED = "TASK_UPDATED";
export const TASK_ASSIGNED = "TASK_ASSIGNED";
export const TASK_UNASSIGNED = "TASK_UNASSIGNED";
export const TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED";
export const TASK_COMPLETED = "TASK_COMPLETED";
export const TASK_CANCELLED = "TASK_CANCELLED";
export const TASK_DELETED = "TASK_DELETED";
export const TASK_COMMENT_ADDED = "TASK_COMMENT_ADDED";
export const TASK_COMMENT_UPDATED = "TASK_COMMENT_UPDATED";
export const TASK_COMMENT_DELETED = "TASK_COMMENT_DELETED";
export const TASK_ATTACHMENT_ADDED = "TASK_ATTACHMENT_ADDED";
export const TASK_DUE_DATE_REMINDER = "TASK_DUE_DATE_REMINDER";
export const TASK_OVERDUE = "TASK_OVERDUE";
export const TASK_PRIORITY_CHANGED = "TASK_PRIORITY_CHANGED";
export const TASK_MENTION = "TASK_MENTION";

// Proposal notification types
export const PROPOSAL_CREATED = "PROPOSAL_CREATED";
export const PROPOSAL_UPDATED = "PROPOSAL_UPDATED";
export const PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED";
export const PROPOSAL_RECEIVED = "PROPOSAL_RECEIVED";
export const PROPOSAL_UNDER_REVIEW = "PROPOSAL_UNDER_REVIEW";
export const PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED";
export const PROPOSAL_REJECTED = "PROPOSAL_REJECTED";
export const PROPOSAL_APPROVED = "PROPOSAL_APPROVED";
export const PROPOSAL_DECLINED = "PROPOSAL_DECLINED";
export const PROPOSAL_WITHDRAWN = "PROPOSAL_WITHDRAWN";
export const PROPOSAL_CANCELLED = "PROPOSAL_CANCELLED";
export const PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED";
export const PROPOSAL_COUNTER_OFFER = "PROPOSAL_COUNTER_OFFER";
export const PROPOSAL_NEGOTIATION = "PROPOSAL_NEGOTIATION";
export const PROPOSAL_AWARDED = "PROPOSAL_AWARDED";
export const PROPOSAL_MENTION = "PROPOSAL_MENTION";

// Message notification types
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
export const MESSAGE_READ = "MESSAGE_READ";
export const MESSAGE_DELETED = "MESSAGE_DELETED";
export const MESSAGE_EDITED = "MESSAGE_EDITED";
export const MESSAGE_REACTION = "MESSAGE_REACTION";
export const MESSAGE_MENTION = "MESSAGE_MENTION";
export const MESSAGE_REPLY = "MESSAGE_REPLY";
export const MESSAGE_THREAD_UPDATED = "MESSAGE_THREAD_UPDATED";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const CONVERSATION_UPDATED = "CONVERSATION_UPDATED";
export const CONVERSATION_DELETED = "CONVERSATION_DELETED";

// Payment notification types
export const PAYMENT_INITIATED = "PAYMENT_INITIATED";
export const PAYMENT_PROCESSING = "PAYMENT_PROCESSING";
export const PAYMENT_COMPLETED = "PAYMENT_COMPLETED";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_CANCELLED = "PAYMENT_CANCELLED";
export const PAYMENT_REFUNDED = "PAYMENT_REFUNDED";
export const PAYMENT_PARTIALLY_REFUNDED = "PAYMENT_PARTIALLY_REFUNDED";
export const PAYMENT_DECLINED = "PAYMENT_DECLINED";
export const PAYMENT_EXPIRED = "PAYMENT_EXPIRED";
export const PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED";
export const PAYMENT_CAPTURED = "PAYMENT_CAPTURED";
export const PAYMENT_VOIDED = "PAYMENT_VOIDED";
export const PAYMENT_CHARGEBACK = "PAYMENT_CHARGEBACK";
export const PAYMENT_DISPUTE = "PAYMENT_DISPUTE";
export const PAYMENT_REMINDER = "PAYMENT_REMINDER";
export const PAYMENT_OVERDUE = "PAYMENT_OVERDUE";
export const PAYMENT_RECEIVED = "PAYMENT_RECEIVED";
export const PAYMENT_SCHEDULED = "PAYMENT_SCHEDULED";
export const PAYMENT_RECURRING = "PAYMENT_RECURRING";

// User/account notification types
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_UPDATED = "USER_UPDATED";
export const USER_DELETED = "USER_DELETED";
export const USER_SUSPENDED = "USER_SUSPENDED";
export const USER_BANNED = "USER_BANNED";
export const USER_REACTIVATED = "USER_REACTIVATED";
export const USER_ROLE_CHANGED = "USER_ROLE_CHANGED";
export const USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED";
export const USER_EMAIL_CHANGED = "USER_EMAIL_CHANGED";
export const USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED";
export const USER_PHONE_VERIFIED = "USER_PHONE_VERIFIED";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_PASSWORD_RESET = "USER_PASSWORD_RESET";
export const USER_PASSWORD_RESET_REQUESTED = "USER_PASSWORD_RESET_REQUESTED";
export const USER_TWO_FACTOR_ENABLED = "USER_TWO_FACTOR_ENABLED";
export const USER_TWO_FACTOR_DISABLED = "USER_TWO_FACTOR_DISABLED";
export const USER_NEW_DEVICE_LOGIN = "USER_NEW_DEVICE_LOGIN";
export const USER_SECURITY_ALERT = "USER_SECURITY_ALERT";

// System notification types
export const SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT";
export const SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE";
export const SYSTEM_UPDATE = "SYSTEM_UPDATE";
export const SYSTEM_ALERT = "SYSTEM_ALERT";
export const SYSTEM_WARNING = "SYSTEM_WARNING";
export const SYSTEM_ERROR = "SYSTEM_ERROR";

// Review notification types
export const REVIEW_REQUESTED = "REVIEW_REQUESTED";
export const REVIEW_RECEIVED = "REVIEW_RECEIVED";
export const REVIEW_SUBMITTED = "REVIEW_SUBMITTED";
export const REVIEW_UPDATED = "REVIEW_UPDATED";
export const REVIEW_DELETED = "REVIEW_DELETED";
export const REVIEW_RESPONSE = "REVIEW_RESPONSE";
export const REVIEW_REMINDER = "REVIEW_REMINDER";

// File notification types
export const FILE_UPLOADED = "FILE_UPLOADED";
export const FILE_DOWNLOADED = "FILE_DOWNLOADED";
export const FILE_DELETED = "FILE_DELETED";
export const FILE_SHARED = "FILE_SHARED";
export const FILE_UNSHARED = "FILE_UNSHARED";
export const FILE_VIEWED = "FILE_VIEWED";

/**
 * All valid notification types.
 */
export const NOTIFICATION_TYPES = [
  // General
  INFO,
  SUCCESS,
  WARNING,
  ERROR,
  CRITICAL,
  // Task
  TASK_CREATED,
  TASK_UPDATED,
  TASK_ASSIGNED,
  TASK_UNASSIGNED,
  TASK_STATUS_CHANGED,
  TASK_COMPLETED,
  TASK_CANCELLED,
  TASK_DELETED,
  TASK_COMMENT_ADDED,
  TASK_COMMENT_UPDATED,
  TASK_COMMENT_DELETED,
  TASK_ATTACHMENT_ADDED,
  TASK_DUE_DATE_REMINDER,
  TASK_OVERDUE,
  TASK_PRIORITY_CHANGED,
  TASK_MENTION,
  // Proposal
  PROPOSAL_CREATED,
  PROPOSAL_UPDATED,
  PROPOSAL_SUBMITTED,
  PROPOSAL_RECEIVED,
  PROPOSAL_UNDER_REVIEW,
  PROPOSAL_ACCEPTED,
  PROPOSAL_REJECTED,
  PROPOSAL_APPROVED,
  PROPOSAL_DECLINED,
  PROPOSAL_WITHDRAWN,
  PROPOSAL_CANCELLED,
  PROPOSAL_EXPIRED,
  PROPOSAL_COUNTER_OFFER,
  PROPOSAL_NEGOTIATION,
  PROPOSAL_AWARDED,
  PROPOSAL_MENTION,
  // Message
  MESSAGE_RECEIVED,
  MESSAGE_SENT,
  MESSAGE_DELIVERED,
  MESSAGE_READ,
  MESSAGE_DELETED,
  MESSAGE_EDITED,
  MESSAGE_REACTION,
  MESSAGE_MENTION,
  MESSAGE_REPLY,
  MESSAGE_THREAD_UPDATED,
  NEW_CONVERSATION,
  CONVERSATION_UPDATED,
  CONVERSATION_DELETED,
  // Payment
  PAYMENT_INITIATED,
  PAYMENT_PROCESSING,
  PAYMENT_COMPLETED,
  PAYMENT_FAILED,
  PAYMENT_CANCELLED,
  PAYMENT_REFUNDED,
  PAYMENT_PARTIALLY_REFUNDED,
  PAYMENT_DECLINED,
  PAYMENT_EXPIRED,
  PAYMENT_AUTHORIZED,
  PAYMENT_CAPTURED,
  PAYMENT_VOIDED,
  PAYMENT_CHARGEBACK,
  PAYMENT_DISPUTE,
  PAYMENT_REMINDER,
  PAYMENT_OVERDUE,
  PAYMENT_RECEIVED,
  PAYMENT_SCHEDULED,
  PAYMENT_RECURRING,
  // User
  USER_REGISTERED,
  USER_UPDATED,
  USER_DELETED,
  USER_SUSPENDED,
  USER_BANNED,
  USER_REACTIVATED,
  USER_ROLE_CHANGED,
  USER_PASSWORD_CHANGED,
  USER_EMAIL_CHANGED,
  USER_EMAIL_VERIFIED,
  USER_PHONE_VERIFIED,
  USER_LOGIN,
  USER_LOGOUT,
  USER_LOGIN_FAILED,
  USER_PASSWORD_RESET,
  USER_PASSWORD_RESET_REQUESTED,
  USER_TWO_FACTOR_ENABLED,
  USER_TWO_FACTOR_DISABLED,
  USER_NEW_DEVICE_LOGIN,
  USER_SECURITY_ALERT,
  // System
  SYSTEM_ANNOUNCEMENT,
  SYSTEM_MAINTENANCE,
  SYSTEM_UPDATE,
  SYSTEM_ALERT,
  SYSTEM_WARNING,
  SYSTEM_ERROR,
  // Review
  REVIEW_REQUESTED,
  REVIEW_RECEIVED,
  REVIEW_SUBMITTED,
  REVIEW_UPDATED,
  REVIEW_DELETED,
  REVIEW_RESPONSE,
  REVIEW_REMINDER,
  // File
  FILE_UPLOADED,
  FILE_DOWNLOADED,
  FILE_DELETED,
  FILE_SHARED,
  FILE_UNSHARED,
  FILE_VIEWED,
] as const;

/**
 * Checks if a type is a valid notification type.
 */
export const isValidNotificationType = (type: string): boolean => {
  return (NOTIFICATION_TYPES as readonly string[]).includes(type);
};

/**
 * Checks if a type is a task notification type.
 */
export const isTaskNotification = (type: string): boolean => {
  return type.startsWith("TASK_");
};

/**
 * Checks if a type is a proposal notification type.
 */
export const isProposalNotification = (type: string): boolean => {
  return type.startsWith("PROPOSAL_");
};

/**
 * Checks if a type is a message notification type.
 */
export const isMessageNotification = (type: string): boolean => {
  return type.startsWith("MESSAGE_") || type.startsWith("CONVERSATION_") || type === "NEW_CONVERSATION";
};

/**
 * Checks if a type is a payment notification type.
 */
export const isPaymentNotification = (type: string): boolean => {
  return type.startsWith("PAYMENT_");
};

/**
 * Consolidated notification type constants object for convenient lookup.
 */
export const NotificationTypes = {
  // General
  INFO,
  SUCCESS,
  WARNING,
  ERROR,
  CRITICAL,
  // Task
  TASK_CREATED,
  TASK_UPDATED,
  TASK_ASSIGNED,
  TASK_UNASSIGNED,
  TASK_STATUS_CHANGED,
  TASK_COMPLETED,
  TASK_CANCELLED,
  TASK_DELETED,
  TASK_COMMENT_ADDED,
  TASK_COMMENT_UPDATED,
  TASK_COMMENT_DELETED,
  TASK_ATTACHMENT_ADDED,
  TASK_DUE_DATE_REMINDER,
  TASK_OVERDUE,
  TASK_PRIORITY_CHANGED,
  TASK_MENTION,
  // Proposal
  PROPOSAL_CREATED,
  PROPOSAL_UPDATED,
  PROPOSAL_SUBMITTED,
  PROPOSAL_RECEIVED,
  PROPOSAL_UNDER_REVIEW,
  PROPOSAL_ACCEPTED,
  PROPOSAL_REJECTED,
  PROPOSAL_APPROVED,
  PROPOSAL_DECLINED,
  PROPOSAL_WITHDRAWN,
  PROPOSAL_CANCELLED,
  PROPOSAL_EXPIRED,
  PROPOSAL_COUNTER_OFFER,
  PROPOSAL_NEGOTIATION,
  PROPOSAL_AWARDED,
  PROPOSAL_MENTION,
  // Message
  MESSAGE_RECEIVED,
  MESSAGE_SENT,
  MESSAGE_DELIVERED,
  MESSAGE_READ,
  MESSAGE_DELETED,
  MESSAGE_EDITED,
  MESSAGE_REACTION,
  MESSAGE_MENTION,
  MESSAGE_REPLY,
  MESSAGE_THREAD_UPDATED,
  NEW_CONVERSATION,
  CONVERSATION_UPDATED,
  CONVERSATION_DELETED,
  // Payment
  PAYMENT_INITIATED,
  PAYMENT_PROCESSING,
  PAYMENT_COMPLETED,
  PAYMENT_FAILED,
  PAYMENT_CANCELLED,
  PAYMENT_REFUNDED,
  PAYMENT_PARTIALLY_REFUNDED,
  PAYMENT_DECLINED,
  PAYMENT_EXPIRED,
  PAYMENT_AUTHORIZED,
  PAYMENT_CAPTURED,
  PAYMENT_VOIDED,
  PAYMENT_CHARGEBACK,
  PAYMENT_DISPUTE,
  PAYMENT_REMINDER,
  PAYMENT_OVERDUE,
  PAYMENT_RECEIVED,
  PAYMENT_SCHEDULED,
  PAYMENT_RECURRING,
  // User
  USER_REGISTERED,
  USER_UPDATED,
  USER_DELETED,
  USER_SUSPENDED,
  USER_BANNED,
  USER_REACTIVATED,
  USER_ROLE_CHANGED,
  USER_PASSWORD_CHANGED,
  USER_EMAIL_CHANGED,
  USER_EMAIL_VERIFIED,
  USER_PHONE_VERIFIED,
  USER_LOGIN,
  USER_LOGOUT,
  USER_LOGIN_FAILED,
  USER_PASSWORD_RESET,
  USER_PASSWORD_RESET_REQUESTED,
  USER_TWO_FACTOR_ENABLED,
  USER_TWO_FACTOR_DISABLED,
  USER_NEW_DEVICE_LOGIN,
  USER_SECURITY_ALERT,
  // System
  SYSTEM_ANNOUNCEMENT,
  SYSTEM_MAINTENANCE,
  SYSTEM_UPDATE,
  SYSTEM_ALERT,
  SYSTEM_WARNING,
  SYSTEM_ERROR,
  // Review
  REVIEW_REQUESTED,
  REVIEW_RECEIVED,
  REVIEW_SUBMITTED,
  REVIEW_UPDATED,
  REVIEW_DELETED,
  REVIEW_RESPONSE,
  REVIEW_REMINDER,
  // File
  FILE_UPLOADED,
  FILE_DOWNLOADED,
  FILE_DELETED,
  FILE_SHARED,
  FILE_UNSHARED,
  FILE_VIEWED,
  // Collections
  ALL: NOTIFICATION_TYPES,
  // Helpers
  isValid: isValidNotificationType,
  isTask: isTaskNotification,
  isProposal: isProposalNotification,
  isMessage: isMessageNotification,
  isPayment: isPaymentNotification,
} as const;

export default NotificationTypes;
